AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19
  UseHashRocketsWithSymbolValues: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Lambda:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/PredicateName:
  NamePrefixBlacklist: []

Style/ClassAndModuleCamelCase:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/MultilineBlockLayout:
  Enabled: false

Style/SpaceAroundBlockParameters:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Lint/EndAlignment:
  AlignWith: "variable"

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Enabled: False

Metrics/ClassLength:
  Max: 100
